# 2018-01-29 - Intégration d'un classifier MNIST
---
J'ai résolu le problème d'assignation des données à x_train en créant toute la base d'apprentissage dans une boucle for.  
Nouveau problème : je n'arrive pas à réaliser correctement la multiplication des poids (theta) et des valeurs (x) pour calculer les hypothèses à l'aide de la fonction :

    tf.matmul()
    
Ce [lien](https://stackoverflow.com/questions/40717614/multiplication-of-tensors-in-a-python-list-with-a-constant-variable-in-tensorflo) propose d'utiliser la fonction ([API](https://www.tensorflow.org/api_docs/python/tf/map_fn)) :

    tf.map_fn()

# 2018-01-30 - TensorFlow (classifier)
---

# 2018-01-31 - TensorFlow (apprentissage)
---
Pour ouvrir le moniteur de ressources sous Ubuntu :

    gnome-system-monitor

# 2018-02-01
---
J'ai un problème pour charger mon graph TensorFlow, alors que ça fonctionnait hier :

    with tf.Session() as sess:
        saver.restore(sess, "/home/pimt/Documents/Notebooks/TF_graph_logpolar.ckpt")
        print("Model restored.")
        
Réponds une erreur :

    InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [480,10] rhs shape= [76,10]
    
J'ai trouvé une piste de solution [ici](https://stackoverflow.com/questions/41992132/tensorflow-error-when-restoring-trained-model-for-eval-invalid-shapes-issue).  
Il semble que ce soit la manière d'enregistrer le graph (itération par itération ou uniquement la dernière itération) qui causait ce problème. J'ai placé l'enregistrement dans la boucle d'apprentissage :

    for it in range(iterations):
        (...)
    # Sauvegarder le graph
    save_path = saver.save(sess, "/home/pimt/Documents/Notebooks/TF_graph_logpolar.ckpt")
    print("Model saved in file: %s" % save_path)
    
à :

    for it in range(iterations):
        (...)
        # Sauvegarder le graph
        save_path = saver.save(sess, "/home/pimt/Documents/Notebooks/TF_graph_logpolar.ckpt")
        print("Model saved in file: %s" % save_path)
---
J'ai un problème avec mon tenseur weights_detect qui output des valeurs nulles après apprentissage : 

        print(weights_detect.eval())
        > [[ nan  nan]
         [ nan  nan]
         [ nan  nan]
         ..., 
         [ nan  nan]
         [ nan  nan]
         [ nan  nan]]
         
 En relancant un petit apprentissage avec peu d'itérations et en imprimant weight_detect à chaque itération, j'observe que ses valeurs augmentent sans cesse, "nan" devant correspondre à des valeurs trop grandes pour TensorFlow : 
 
     (...)
     iteration # 2
        [[    9.27591896     7.34605074]
         [    2.1299746      3.18954992]
         [  -28.4733963    -21.6524086 ]
         ...,
     (...)
     iteration # 10
        [[ -8.89382765e+12  -2.33215020e+12]
         [  2.08348093e+12  -2.88921045e+13]
         [ -9.59871294e+12   6.16527666e+13]
         ...,
     (...)
     iteration # 20
        [[ -4.62158587e+27   1.31747874e+28]
         [  1.40140265e+26  -1.75823946e+27]
         [  2.30720612e+28  -5.83924630e+28]
         ...,
     (...)
     iteration # 25
        [[ -3.34893110e+34              nan]
         [ -1.39562726e+35              nan]
         [  2.42714347e+35              nan]
         ..., 
         [ -1.45280634e+36              nan]
         [  6.02105767e+36              nan]
         [  9.47063190e+35              nan]]
     (...)
     iteration # 26
        [[ nan  nan]
         [ nan  nan]
         [ nan  nan]
         ..., 
         [ nan  nan]
         [ nan  nan]
         [ nan  nan]]
         
A priori j'ai en partie réglé ce problème en normalisant les données :

    def normalize(array):
        normalized_array = (array - np.mean(array)) / np.std(array)
        return normalized_array
        
    (...)
    v = phi_vectorial @ np.ravel(image)
    values += [normalize(v)]
    
    > iteration # 26
        [[ 0.0074468   0.04578442]
         [-0.0217662   0.01849911]
         [-0.01777184  0.02355972]
         ..., 
         [-0.26072639 -0.43131059]
         [ 0.60237288  1.39775634]
         [ 0.14805925 -1.01771271]]
         
 Mais après un grand nombre d'itérations, les poids continuent quand même de grandir : 
 
     iteration # 40
        [[  0.24413383   0.27580678]
         [  1.10672057   1.07873833]
         [ -2.87931776  -2.62879276]
         ..., 
         [-19.31992149 -18.26003456]
         [ 43.26939011  40.83727264]
         [-10.96153641 -11.68423462]]
     (...)
     iteration # 99
        [[  2604173.75     2418676.    ]
         [   350845.625     325854.3125]
         [ -3505418.5     -3255725.5   ]
         ..., 
         [ 21479828.      19949802.    ]
         [-56334776.     -52322008.    ]
         [ 13729081.      12751140.    ]]

# 2018-02-02
---

---
# To Do
+ Partager le groupe Mendely avec Daucé et Perrinet
+ S'inscrire sur la liste de diffusion de l'INS
+ Traduire le rapport en anglais?
+ ~~Signer fiche de présence du mois de janvier~~
### Waveimage_TensorFlow
+ ~~Traduire le script de régression linéaire haut-niveau en script bas-niveau~~
    + ~~Résoudre le problème d'assignation des données à x_train~~
    + ~~Résoudre le problème de calcul matriciel pour l'élaboration de l'hypothèse~~
+ Créer un classifier pour stopper les saccades lorsque la cible est identifiée
    + ~~Créer le classifier~~
    + ~~Evaluer le classifier~~
    + **Introduire les saccades**
+ Créer une ou plusieurs méthodes pour introduire du bruit dans les images
+ Traduire en modèle probabiliste
+ ~~Traduire l'input en logPolar~~
+ ~~Enregistrer les poids après apprentissage~~
+ ~~Charger le graph après apprentissage~~
+ **Résoudre le problème de chargement du graph**
+ ~~Résoudre le problème de valeurs nulles augmentant exponentiellement de weights_detect~~ -> Réglé seulement temporairement ?
### Waveimage-tensorflow-pow3-encoding_P3ver
+ Créer un graphique : nombre de saccades nécessaires à atteindre la cible en fonction de sa distance du point de fixation
+ Créer un classifier pour stopper les saccades lorsque la cible est identifiée
    + ~~Créer le classifier~~
    + Entrainer le classifier
    + Evaluer les performances du classifier
+ Traduire le modèle en modèle probabiliste
+ Créer une ou plusieurs méthodes pour introduire du bruit dans les images
+ Réaliser une transformation coordonnée -> degrés et adapter le modèle pour les utiliser
### mnist-logPolar-encoding
+ Ecrire un script réalisant un apprentissage par régression linéaire en utilisant les sorties de la partie "Energy"
+ Intégrer un bruit écologique aux images (cf Najemnik2005 (chercher la méthode utilisée dans les sources); librairie [SLIP](https://nbviewer.jupyter.org/github/bicv/SLIP/blob/master/SLIP.ipynb) de Laurent)
### Rapport M2a
+ **Ecrire une ébauche d'introduction**
+ Créer les fichers pour les autres chapitres
    + ~~Matériel et méthodes~~
    + Résultats
    + Discussion
    + Annexes
+ Ecrire une ébauche de matériel
+ Ecrire une ébauche de méthodes

---
# A lire
+ http://bethgelab.org/media/publications/Kuemmerer_High_Low_Level_Fixations_ICCV_2017.pdf
+ https://pdfs.semanticscholar.org/0182/5573781674bcf85d0f5d2ec456842f75ad3c.pdf
+ Schmidhuber, 1991 (voir mail Daucé)
+ Parr and Friston, 2017 (voir mail Perrinet)
+ http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003005#s1
+ http://rpg.ifi.uzh.ch/docs/RAL18_Loquercio.pdf
+ https://www.nature.com/articles/sdata2016126
+ [Liu et al., 2016](http://ieeexplore.ieee.org/document/7762165/?reload=true) : Learning to Predict Eye Fixations via Multiresolution Convolutional Neural Networks
### Magnocellular pathway function  
+ [Selective suppression of the magnocellular visual pathway during saccadic eye movements](http://www.nature.com.lama.univ-amu.fr/articles/371511a0), Burr1994
+ [On Identifying Magnocellular and Parvocellular Responses on the Basis of Contrast-Response Functions](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3004196/), Skottun2011
+ [Review: Steady and pulsed pedestals, the how and why of post-receptoral pathway separation](http://jov.arvojournals.org/article.aspx?articleid=2191890), Pokorny2011
+ [An evolving view of duplex vision: separate but interacting cortical pathways for perception and action](http://www.sciencedirect.com/science/article/pii/S0959438804000340?via%3Dihub), Goodale2004
+ [Quantitative measurement of saccade amplitude, duration, and velocity](http://n.neurology.org/content/25/11/1065), Baloh1975

---
# Satellites